services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3000"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=465
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
